### ISSUE TITLE
puppy forces full percent encoding in path segments

### ISSUE THREAD

**Issue by veksha** [treeform/puppy#111]
trying to fetch `https://www.elyrics.net/read/0-9/$uicideboy$-lyrics/[whispers-indistinctly]-lyrics.html`
i get code 404
(Windows OS)

it is because puppy forces percent encoding of a lot of chars ($, [, ], etc..)

browsers don't do it.
can be checked in chromium console:
<img width="221" alt="image" src="https://github.com/treeform/puppy/assets/275333/56774163-a2ef-4b64-a5c4-c0a40a09c3b2">

i think the same is true for query params and fragment.. browsers for some reason act different when encoding them. maybe RFC allows it or it is made so for compatibility.

**Comment by guzba** [comment]
This is fixed in release 2.1.2. Feel free to re-open if things are still not working as expected.
