### ISSUE TITLE
Stacksmashing with simple request

### ISSUE THREAD

**Issue by beef331** [treeform/puppy#14]
On linux with release doing the following will cause a stack smash error
```nim
import puppy
discard fetch("https://unity3d.com/get-unity/download/archive")
```

**Comment by beef331** [comment]
With further testing it seems to be a product of using `refc`, using `arc` or `orc` to stops it from happening.

**Comment by treeform** [comment]
I am pretty sure this got fixed with: https://github.com/treeform/puppy/pull/16

Please reopen issues the issue if you still have trouble.
