### ISSUE TITLE
Problems when I use other machines

### ISSUE THREAD

**Issue by Yihsiwei** [treeform/puppy#37]
I want to know that I only want to send a get request, but it is HTTPS. How can I be universal

<img width="415" alt="da773ec41e80eb8257e89bf0a90ad2a" src="https://user-images.githubusercontent.com/59053987/140472798-e9940831-4baa-4318-81c6-7bd4cf19c148.png">

**Comment by guzba** [comment]
From some Googling, that HRESULT code appears to be Windows saying 0x80072ee7= "The server name or address could not be resolved

**Comment by Yihsiwei** [comment]
> From some Googling, that HRESULT code appears to be Windows saying 0x80072ee7= "The server name or address could not be resolved"
> 
> Do you maybe have connectivity issues or a proxy or VPN or some other thing possibly causing trouble?

Thank you very much. I'll ask my friend if his computer used proxy or VPN at that time

**Comment by Yihsiwei** [comment]
> From some Googling, that HRESULT code appears to be Windows saying 0x80072ee7= "The server name or address could not be resolved"
> 
> Do you maybe have connectivity issues or a proxy or VPN or some other thing possibly causing trouble?

yes,He did open VPN. Thank you very much

**Comment by treeform** [comment]
Closing this issue. Its some sort of VPN connection thing from windows. 

Feel free to reopen if you have still have issues related to puppy.
