### ISSUE TITLE
Hardcoded `get` verb in $ proc

### ISSUE THREAD

**Issue by srozb** [treeform/puppy#44]
Hi,
I think echoing `Request` will always show the verb being `get` no matter what verb actually is used. See [this line](https://github.com/treeform/puppy/blob/master/src/puppy.nim#L49).

This is very confusing. Would also be very helpful to print post body if defined.

**Comment by guzba** [comment]
Sorry for the hardcoded value. That was an oversight on our part. Thanks for the PR and test to fix this.
