### ISSUE TITLE
SIGSEGV on Apple Silicon ( M1 )

### ISSUE THREAD

**Issue by heinthanth** [treeform/puppy#59]
I've tried to compile and run simple code like below:

```nim
import puppy

echo fetch("https://ifconfig.me")
```

On Intel mac ( with rosetta2 ) compiled with x86-64 nim, it works fine!
But when compiled with arm64 nim, it resulted in SIGSEGV. 

ARM64:

<img width="654" alt="Screen Shot 2022-01-27 at 12 58 23 PM" src="https://user-images.githubusercontent.com/43804263/151304320-4ae5cc0f-9cd9-4ca0-9a5b-fc3ed121ca37.png">

AMD64:

<img width="739" alt="Screen Shot 2022-01-27 at 12 59 28 PM" src="https://user-images.githubusercontent.com/43804263/151304335-7cd10e80-be7d-457b-93ff-e90d3fc1c6fb.png">

I traced and found out `objc_msgSend` is causing the problem. But can't solve since I'm not quite familiar with macOS system lib and objc.

https://github.com/treeform/puppy/blob/0efd3cef961a91e6b47117cfa6acf026cdb775a9/src/puppy/macdefs.nim#L72-L76

Hope you can fix it 🙇

**Comment by guzba** [comment]
We noticed this with https://github.com/treeform/windy too. We figured out the issue over there and are porting it here too now.

**Comment by guzba** [comment]
Will be tagged tmrw, is late here https://github.com/treeform/puppy/pull/61
