### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by Techno-Fox** [treeform/puppy#67]
Thank you for making an easy http/https library for Nim. I wanted to know how would I be able to use a self signed certificate for https. When ever I try it, it gives me the error.

"SSL peer certificate or SSH remote key was not OK"

**Comment by treeform** [comment]
We don't support self signed certs at the moment. We don't have a need for this so we will probably not add it. Sorry! PRs welcome though.

I recommend going with Let's Encrypt (totally free) or CloudFlare (free tear) for real SSL certs. I use both.

**Comment by Techno-Fox** [comment]
I'm having some issues with the macos side of things. Given my little to no experience with macos, it would make sense. How would you allow insecure certificates on a NSMutableURLRequest. I've tried using setAllowsAnyHTTPSCertificate as
```
proc setAllowsAnyHTTPSCertificate*(self: NSMutableURLRequest)
```

however then I'm getting NSInvalidArgumentException.

**Comment by treeform** [comment]
Add a draft pr and we will take a look.

**Comment by Techno-Fox** [comment]
I'm just waking up. I'll have to add this either tomorrow or in 15 hours ish

**Comment by Techno-Fox** [comment]
I've sent it.

**Comment by drighty** [comment]
see pull request https://github.com/treeform/puppy/pull/84, is it related?

**Comment by guzba** [comment]
Related previous PR: https://github.com/treeform/puppy/pull/68

**Comment by treeform** [comment]
This should be good to go in puppy 1.6.1. Let us know if you still have issues with this.
