### ISSUE TITLE
exception: convert from VT_ARRAY(1D)|VT_UI1 to integer

### ISSUE THREAD

**Issue by alexisad** [treeform/puppy#7]
Windows 10

main.nim:
```nim
import puppy

let req = Request(
    url: parseUrl("http://www.istrolid.com"),
    verb: "get",
    headers: @[Header(key: "Auth", value: "1")]
)
let res = fetch(req)

```

Documents\nimapps\puppy_test\main.nim(8) main
.nimble\pkgs\puppy-1.0.2\puppy.nim(100) fetch
.nimble\pkgs\winim-3.6.0\winim\com.nim(815) variantConverterToInt
.nimble\pkgs\winim-3.6.0\winim\com.nim(741) fromVariant
Error: unhandled exception: convert from VT_ARRAY(1D)|VT_UI1 to integer [VariantConversionError]
Error: execution of an external program failed: 'Documents\nimapps\puppy_test\main.exe '

**Comment by treeform** [comment]
I think we fixed it with, https://github.com/treeform/puppy/commit/0a4f93edeba44c671887ecc5d34614d331c1c0ef please update?

**Comment by alexisad** [comment]
Hi @treeform ,

thanks a lot!
It is working now without exception.
