### ISSUE TITLE
Unix socket support 

### ISSUE THREAD

**Issue by lantos-lgtm** [treeform/puppy#77]
Hey treeform, I just pushed OPT_UNIX_SOCK_PATH into libcurl.nim
https://github.com/Araq/libcurl/commit/7a420498f60a31d99fc8513886ce36c4e8c3a4ae

Is it possible to get unix socket support in libcurl.nim?

I'm using something like this which works.

```nim

type CurlWriteFnHandle* = proc (   
                buffer: cstring,
                size: int,
                count: int,
                outstream: pointer): int {. gcsafe, locks: 0.}

proc defaultCurlWriteFn(
        buffer: cstring,
        size: int,
        count: int,
        outstream: pointer
    ): int =
    let outbuf = cast[ref string](outstream)
    outbuf[] &= buffer
    result = size * count

# can swap this to puppy if puppy supported sockets
proc request*(
            req: Request,
            path: string,
            httpMethod: HttpMethod,
            body: string,
            multipartData: MultipartData,
            useCurl: bool = false,
            headers: HttpHeaders = newHttpHeaders({"Accept": "application/json",
                "Content-Type": "application/json"}),
            curlWriteFn: CurlWriteFnHandle = defaultCurlWriteFn
        ): string =

        let useUnix = docker.baseUrl.startsWith("unix://")
        if useCurl or useUnix:
            let webData: ref string = new string
            let socketPath = ctx.baseUrl[7..ctx.baseUrl.high]
            let curl = easy_init()

            if useUnix:
                discard curl.easy_setopt(OPT_UNIX_SOCKET_PATH,
                        socketPath.cstring)
                discard curl.easy_setopt(OPT_URL, path.cstring)
            else:
                discard curl.easy_setopt(OPT_URL, (docker.baseUrl & "/" & path).cstring)

            discard curl.easy_setopt(OPT_CUSTOMREQUEST, ($httpMethod).cstring)
            discard curl.easy_setopt(OPT_POSTFIELDSIZE, body.len)
            discard curl.easy_setopt(OPT_POSTFIELDS, body)

            var headerChunk: Pslist
            headerChunk = headerChunk.slist_append("Accept: application/json")
            headerChunk = headerChunk.slist_append("Content-Type: application/json")
            discard curl.easy_setopt(OPT_HTTPHEADER, headerChunk);


            discard curl.easy_setopt(OPT_WRITEDATA, webData)
            discard curl.easy_setopt(OPT_WRITEFUNCTION, curlWriteFn)
            discard curl.easy_setopt(OPT_VERBOSE, 1)
            let ret = curl.easy_perform()

            if ret != E_OK:
                raise newException(Defect, $ret & $easy_strerror(ret))

            result = webData[]
            curl.easy_reset()

```

**Comment by treeform** [comment]
I have never used Unix sockets, therefore, I do not think it is a frequently used feature. Do Windows or macOS have Unix socket equivalents? I do not want to increase the size of the library when I do not see a clear benefit. I do not think I will be adding Unix sockets at this time. Sorry.

**Comment by lantos-lgtm** [comment]
> I have never used Unix sockets, therefore, I do not think it is a frequently used feature. Do Windows or macOS have Unix socket equivalents? I do not want to increase the size of the library when I do not see a clear benefit. I do not think I will be adding Unix sockets at this time. Sorry.

Macos does (example; docker macos uses simlink), windows supports it now. It's used quite heavily in unix programs, ( I think most daemons use it, sql, docker...)  

Araq merged my change in libcurl.nim to support it but makes sense not to do it if I'm the only one asking.
ended up patching std/net.nim std/asyncnet.nim to make it work and a custom httpclient.nim

Thanks for considering it though :)

**Comment by eclairevoyant** [comment]
MacOS and Linux have supported Unix sockets forever, and as of Windows 10, [Windows actually supports Unix sockets](https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/) too.
It's a very common protocol for interprocess communication.

**Comment by theAkito** [comment]
UNIX sockets are a thing of the past. No need to hold onto it. The only reason they are not uncommon is because of how certain low-level Linux things sadly work.

If Linux would be modern, there would be no UNIX sockets.

**Comment by eclairevoyant** [comment]
Look, I'm not here to argue philosophical discussions. I don't even have a problem if the maintainer doesn't want to include Unix socket support in this library. I commented to point out that a) there is cross-platform support and b) it's not an infrequently used functionality. And I wouldn't bother commenting if I wasn't planning on using them - either way I'll likely end up implementing support for myself.

**Comment by lantos-lgtm** [comment]
> UNIX sockets are a thing of the past. No need to hold onto it. The only reason they are not uncommon is because of how certain low-level Linux things sadly work.
> 
> If Linux would be modern, there would be no UNIX sockets.

I don't think this this is exactly true, I believe the following still use unix sockets
- Docker
- PhpFpm
- Mysql
- X11
- Nginx
- PulseAudio (?)
- Systemd (?)

This was a while ago but if IRC I ended up finding that there isn't really anything that needed to be changed so that puppy supported sockets. The issue with the sockets ended up being a problem in the std/net library. It was just not dialling correctly.

https://github.com/nim-lang/Nim/issues/20062
