### ISSUE TITLE
could not load: libobjc.dylib

### ISSUE THREAD

**Issue by iffy** [treeform/puppy#85]
I'm not expecting you to fix this unless something obvious jumps out at you, but thought I'd file it in case you have an idea.

- I introduced puppy as a dependency in my app
- I build the app on GitHub using the macos-10.15 builder
- I'm running the app on a macOS 10.14.6 machine

After introducing puppy, I get the following error:

```
could not load: libobjc.dylib
```

I have no trouble building and running stuff with puppy on the macOS 10.14.6 machine. Feel free to close if this is a wontfix.

**Comment by treeform** [comment]
I don't think macOS is "forward compatible" for many things. You should build on the OS version you want your things to run.

Does a build on `macOS 10.14.6` work on `macOS 10.15`, it should do that but not the other way around.
