### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by juancarlospaco** [treeform/puppy#9]
How to POST `multipart/form-data` ?, is it supported ?.

**Comment by guzba** [comment]
In the end that body format ends up as a string like json or form-urlencoded data post bodies do so you could produce the correct post body string and set the correct header and it'd work fine. There just isn't APIs in puppy to make that easier.

**Comment by guzba** [comment]
Update on this issue. We've added some helpers for building a multipart request body and have added an example showing how to do `multipart/form-data` here: https://github.com/treeform/puppy/pull/98/files

This is tagged in Puppy 2.0.3
